"""__init__.py для модуля keyboards"""

from .main_menu import (
    get_role_selection_keyboard,
    get_student_main_menu,
    get_employer_main_menu,
    get_back_to_menu_keyboard,
    get_course_selection_keyboard,
    get_specialization_keyboard,
    get_company_field_keyboard,
    get_contact_admin_keyboard,
)
from .job_search import (
    get_job_filters_keyboard,
    get_sphere_selection_keyboard,
    get_format_selection_keyboard,
    get_salary_selection_keyboard,
    get_vacancy_list_keyboard,
    get_vacancy_detail_keyboard,
    get_application_type_keyboard,
    get_career_center_categories_keyboard,
    get_material_list_keyboard,
    get_material_detail_keyboard,
    get_back_to_vacancy_list_keyboard,
)
from .employer_menu import (
    get_employer_main_menu_keyboard,
    get_vacancy_creation_steps_keyboard,
    get_vacancy_draft_keyboard,
    get_tariff_selection_keyboard,
    get_tariff_info_keyboard,
    get_premium_payment_keyboard,
    get_vacancy_list_employer_keyboard,
    get_vacancy_detail_employer_keyboard,
    get_vacancy_statistics_keyboard,
    get_applications_list_keyboard,
    get_application_detail_keyboard,
    get_company_settings_keyboard,
    get_moderation_decision_keyboard,
    get_back_to_employer_menu_keyboard,
)

__all__ = [
    # Main menu
    "get_role_selection_keyboard",
    "get_student_main_menu",
    "get_employer_main_menu",
    "get_back_to_menu_keyboard",
    "get_course_selection_keyboard",
    "get_specialization_keyboard",
    "get_company_field_keyboard",
    "get_contact_admin_keyboard",
    # Job search
    "get_job_filters_keyboard",
    "get_sphere_selection_keyboard",
    "get_format_selection_keyboard",
    "get_salary_selection_keyboard",
    "get_vacancy_list_keyboard",
    "get_vacancy_detail_keyboard",
    "get_application_type_keyboard",
    "get_career_center_categories_keyboard",
    "get_material_list_keyboard",
    "get_material_detail_keyboard",
    "get_back_to_vacancy_list_keyboard",
    # Employer menu
    "get_employer_main_menu_keyboard",
    "get_vacancy_creation_steps_keyboard",
    "get_vacancy_draft_keyboard",
    "get_tariff_selection_keyboard",
    "get_tariff_info_keyboard",
    "get_premium_payment_keyboard",
    "get_vacancy_list_employer_keyboard",
    "get_vacancy_detail_employer_keyboard",
    "get_vacancy_statistics_keyboard",
    "get_applications_list_keyboard",
    "get_application_detail_keyboard",
    "get_company_settings_keyboard",
    "get_moderation_decision_keyboard",
    "get_back_to_employer_menu_keyboard",
]
